# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyGoogleMap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyGoogleMap
  # 구글맵
  pod 'GoogleMaps'
  # 행정주소 받아오기
  pod 'GooglePlaces'

end
