# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyToastSDWebImage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyToastSDWebImage
	pod 'Toast-Swift', '~> 5.0.0'
  pod 'SDWebImage', '~> 5.0'
  
  
end
